# Wget autogenerated by preomr script
# 2009-09-14 18:57:52.635686
# 
# http://preomr.appspot.com/work/read/list/wget/7154?download

echo "Marche aux Flambeaux"
wget -O "marche-aux-flambeaux.pdf" "http://www.mutopiaproject.org/ftp/ClarkFS/Marche_aux_Flambeaux/Marche_aux_Flambeaux-a4.pdf"

echo "Usquequo Domine"
wget -O "usquequo-domine.pdf" "http://www.mutopiaproject.org/ftp/CouperinF/UsquequoDomine/UsquequoDomine-a4.pdf"

echo "Io gia t'amai , Aria from Rodelinda"
wget -O "io-gia-tamai-aria-from-rodelinda.pdf" "http://www.mutopiaproject.org/ftp/HandelGF/HWV19/IoGiaTAmai/IoGiaTAmai-a4.pdf"

echo "The Silver Swan"
wget -O "the-silver-swan.pdf" "http://www.mutopiaproject.org/ftp/GibbonsO/SilverSwan/SilverSwan-a4.pdf"

