# Wget autogenerated by preomr script
# 2009-09-14 18:58:01.414736
# 
# http://preomr.appspot.com/work/read/list/wget/8001?download

echo "Goldberg Variations - 25"
wget -O "goldberg-variations-25.pdf" "http://www.free-scores.com/PDF/bach-johann-sebastian-goldberg-variations-10799.pdf"

echo "IV rondeaux pour la guitare"
wget -O "iv-rondeaux-pour-la-guitare.pdf" "http://www.free-scores.com/redirection-partition.php?partition=4425"

echo "Fantaisie elégiaque: pour guitare seule"
wget -O "fantaisie-elgiaque-pour-guitare-seule.pdf" "http://www.free-scores.com/redirection-partition.php?partition=5075"

echo "La Traviata - N2 Brindisi"
wget -O "la-traviata-n2-brindisi.pdf" "http://www.free-scores.com/PDF/verdi-giuseppe-traviata-brindisi-9601.pdf"

