# Wget autogenerated by preomr script
# 2009-09-14 18:57:56.650355
# 
# http://preomr.appspot.com/work/read/list/wget/7155?download

echo "Ich elender Mensch, wer wird mich erlosen"
wget -O "ich-elender-mensch-wer-wird-mich-erlosen.pdf" "http://www.musedata.org/cgi-bin/mddata?composer=bach&amp;edition=bg&amp;genre=cant&amp;work=0048&amp;format=print&amp;file=fullscore.pdf"

echo "Symphony No. 2 in D Major"
wget -O "symphony-no-2-in-d-major.pdf" "http://www.musedata.org/cgi-bin/mddata?composer=beet&amp;edition=bh&amp;genre=sym&amp;work=no2&amp;format=pdf&amp;multi=zip"

echo "Symphony No. 3 in E-flat Major - Eroica"
wget -O "symphony-no-3-in-e-flat-major-eroica.pdf" "http://www.musedata.org/cgi-bin/mddata?composer=beet&amp;edition=bh&amp;genre=sym&amp;work=no3&amp;format=pdf&amp;multi=zip"

echo "Das wohltemperirte Clavier, Band II - Prelude and Fugue in D-sharp Minor"
wget -O "das-wohltemperirte-clavier-band-ii-prelude-and-fugue-in-d-sharp-minor.pdf" "http://www.musedata.org/cgi-bin/mddata?composer=bach&amp;edition=bg&amp;genre=keybd/wtc-ii&amp;work=0877&amp;format=pdf&amp;multi=zip"

